//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camphorizon.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesCatalogue
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string OfferHeading { get; set; }
        public string OfferDetails { get; set; }
        public string ImageLink { get; set; }
        public Nullable<short> ImageFor { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<short> SlideOrder { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
