//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camphorizon.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.PackageCancellationTermsMappings = new HashSet<PackageCancellationTermsMapping>();
            this.PackageExclusions = new HashSet<PackageExclusion>();
            this.PackageFacilityMappings = new HashSet<PackageFacilityMapping>();
            this.PackageInclusions = new HashSet<PackageInclusion>();
            this.PackageItineraries = new HashSet<PackageItinerary>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<short> Duration { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<PackageCancellationTermsMapping> PackageCancellationTermsMappings { get; set; }
        public virtual ICollection<PackageExclusion> PackageExclusions { get; set; }
        public virtual ICollection<PackageFacilityMapping> PackageFacilityMappings { get; set; }
        public virtual ICollection<PackageInclusion> PackageInclusions { get; set; }
        public virtual ICollection<PackageItinerary> PackageItineraries { get; set; }
    }
}
